name: DockerHum Login

on:
  workflow_dispatch:

jobs:
  tests2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Java JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Java Version
        run: java -version
      - name: Build Jar and Run Tests
        run: mvn clean install

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: alutard/newtestimage:${{ github.run_number }}
      - name: Upload artifact
        uses: action/upload-artifact@v2
        with:
          name: app.jar
          path: target/*.jar
